# Generated by Django 5.1.7 on 2025-03-12 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
        migrations.AddField(
            model_name="services",
            name="work_image_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="services.images"
            ),
        ),
    ]
